<div class="container-fluid">

<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Quản lý hệ thống <small>chamcom.vn</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Bảng điều khiển
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="fa fa-info-circle"></i>  <strong>Chưa có thông báo nào.</strong> Các thông báo mới sẽ hiện ra ở đây!
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">26</div>
                        <div>Bình luận mới!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">12</div>
                        <div>Đơn hàng mới!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">124</div>
                        <div>Đơn hàng mới!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-support fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">13</div>
                        <div>Giao hàng thành công!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Xem chi tiết</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Biểu đồ</h3>
            </div>
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Số đơn hàng</h3>
            </div>
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
                <div class="text-right">
                    <a href="#">Xem chi tiết <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Số đơn hàng đã hoàn thành</h3>
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <span class="badge">vừa xong</span>
                        <i class="fa fa-fw fa-calendar"></i> Cập nhật
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">4 phút trước</span>
                        <i class="fa fa-fw fa-comment"></i> Bình luận món chính
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">23 phút trước</span>
                        <i class="fa fa-fw fa-truck"></i> Tùng Cheng đã đặt cơm
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">46 phút trước</span>
                        <i class="fa fa-fw fa-money"></i> Bình luận món chính
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">1 giờ trước</span>
                        <i class="fa fa-fw fa-user"></i> Hoàng Anh đã đăng ký
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">2 giờ trước</span>
                        <i class="fa fa-fw fa-check"></i> Krad đã giao hàng thành công
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">Hôm qua</span>
                        <i class="fa fa-fw fa-globe"></i> .cơm đã cứu thế giới như thế nào?
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="badge">2 ngày trước</span>
                        <i class="fa fa-fw fa-check"></i> Bình luận mới...
                    </a>
                </div>
                <div class="text-right">
                    <a href="#">Xem tất cả các hoạt động <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money fa-fw"></i> Bảng giao dịch</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Mã đơn suất cơm</th>
                            <th>Ngày giao cơm</th>
                            <th>Thời gian</th>
                            <th>Giá (VNĐ)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>6969</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>33000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>9696</td>
                            <td>10/21/2014</td>
                            <td>12:30 PM</td>
                            <td>37000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>50000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>30000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>30000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>30000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>30000 VNĐ</td>
                        </tr>
                        <tr>
                            <td>3326</td>
                            <td>10/21/2014</td>
                            <td>11:30 PM</td>
                            <td>30000 VNĐ</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="text-right">
                    <a href="#">Xem tất cả các giao dịch <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->