<!-- Start SideBar-->             
<ul id="sidebar-nav">
	<li><a href="#">Quản trị game</a>
		<ul class="drop" style="<?php if($this->controller == 'index') echo 'display: block;' ?>">
  			<li><a href="/user/index/product"><img src="/images/adminbase/icons/16/comments.png">Danh sách</a></li>
  			<li><a href="/user/index/add-product"><img src="/images/adminbase/icons/16/comments.png">Thêm</a></li>
		</ul>
	</li>
</ul>
<!-- End SideBar -->
<br class="cl" /> 
<script type="text/javascript">
//Menu sidebar
$('#sidebar-nav > li > a').click(function(){
	    if ($(this).attr('class') != 'active'){
	      $('#sidebar-nav li ul').slideUp();
	      $(this).next().slideToggle();
	      $('#sidebar-nav li a').removeClass('active');
	      $(this).addClass('active');
		  return false;
	    }
	  });
</script>
