<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="no-Store">
<!-- Javascript -->
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-1.8.3.min.js') ?>"></script>
<!-- CSS - Setup -->
<link href="<?php echo $this->baseUrl('css/adminbase/style.css'); ?>" rel="stylesheet" type="text/css">
<!-- CSS - Styles -->
<link href="<?php echo $this->baseUrl('css/adminbase/base.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('css/adminbase/forms.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('css/adminbase/extensions.css'); ?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('css/adminbase/lists.css'); ?>" rel="stylesheet" type="text/css">
